$env:SCRAPER_MODE="failed_stores"
$env:FAILED_STORE_RETRY_CONCURRENCY="1"

$env:SCRAPE_CLASSIC_COMBO="1"
$env:CLASSIC_COMBO_PAGE_FALLBACK="0"
$env:CLASSIC_COMBO_DETAIL_CONCURRENCY="1"
$env:SCRAPE_LOCATION_TIMEOUT_SECONDS="480"

.\.venv\Scripts\python.exe .\scraper.py
