$env:FIVE_GUYS_DIRECTORY_ROOT_URL="https://restaurants.fiveguys.com/index.html"
$env:FIVE_GUYS_MAX_LOCATIONS="0"
$env:SCRAPER_MODE="full_with_reviews"
$env:GOOGLE_MAPS_REVIEW_LIMIT="100"

$env:SCRAPE_CONCURRENCY="3"
$env:GOOGLE_MAPS_SCRAPE_CONCURRENCY="2"
$env:SCRAPE_CLASSIC_COMBO="1"
$env:CLASSIC_COMBO_PAGE_FALLBACK="0"
$env:CLASSIC_COMBO_DETAIL_CONCURRENCY="1"
$env:CLASSIC_COMBO_PRESENT_TIMEOUT_SECONDS="120"
$env:CLASSIC_COMBO_PRESENT_RENDER_ATTEMPTS="3"
$env:CLASSIC_COMBO_FALLBACK_TIMEOUT_SECONDS="10"
$env:CLASSIC_COMBO_RENDER_ATTEMPTS="1"
$env:SCRAPE_LOCATION_TIMEOUT_SECONDS="480"

Remove-Item Env:ORDER_CLOUDFLARE_HELPER_URL,Env:ORDER_CLOUDFLARE_HELPER_ENABLED -ErrorAction SilentlyContinue

.\.venv\Scripts\python.exe .\scraper.py
